---
restylers:
  - name: black
    image: restyled/restyler-black:v19.10b0
    command:
      - black --line-length 120
    arguments: []
    include:
      - "**/*.py"
    interpreters:
      - python
