---
restylers:
  - name: black
    image: restyled/restyler-black:v19.10b0
    command:
      - black
    arguments:
      - "--line-length 120"
    include:
      - "**/*.py"
    interpreters:
      - python
