version: "2"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: ps01
    environment:
      - POSTGRES_PASSWORD=contraseña
    volumes:
      - vol_postgres:/var/lib/postgresql/data
  web:
    build: .
    container_name: dg01
    restart: always
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn myproject.wsgi -b 0.0.0.0:8000"
    depends_on:
      - 'db'
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    container_name: ng01
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - 'web'

volumes:
  vol_postgres:
    driver: local