version: "2"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: ps01
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - vol_postgres:/var/lib/postgresql/data
  web:
    build:
      context: ./config/web/
    container_name: dg01
    environment:
      - PROJECT_NAME
      - DJANGO_SETTINGS_MODULE
      - POSTGRES_PASSWORD
      - ENVIRONMENT
    restart: always
    command: /config/entry_point.sh
    # command: tail -f /dev/null
    depends_on:
      - 'db'
    volumes:
      - vol_static/:/static

      # Development volumes
      - ./config/web/.coveralls.yml:/src/.coveralls.yml
      - ./src:/src
      - ./fixtures:/fixtures
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    container_name: ng01
    restart: always
    ports:
      - "$PORT:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - vol_static:/static
    depends_on:
      - 'web'

volumes:
  vol_postgres:
    driver: local
  vol_static:
    driver: local
