version: "2"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: ps01
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - vol_postgres:/var/lib/postgresql/data
  web:
    build: .
    container_name: dg01
    environment:
      - POSTGRES_PASSWORD
    restart: always
    command: ./entry_point.sh
    # command: tail -f /dev/null
    depends_on:
      - 'db'
    volumes:
      - ./config/web/entry_point.sh:/src/entry_point.sh
      - ./src:/src
      - ./fixtures:/fixtures
      - vol_static/:/static
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    container_name: ng01
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - vol_static:/static
    depends_on:
      - 'web'

volumes:
  vol_postgres:
    driver: local
  vol_static:
    driver: local
