# Generated by Django 2.2.2 on 2020-04-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_modification_datetime", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("status", models.IntegerField(choices=[(0, "pending"), (1, "assigned"), (2, "sent")], default=0,),),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="transactions.Request",),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_modification_datetime", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("status", models.IntegerField(choices=[(0, "pending"), (1, "assigned"), (2, "sent")], default=0,),),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="supplies", to="products.Product",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
