# Generated by Django 2.2.2 on 2020-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200410_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'assigned'), (2, 'sent')], default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'assigned'), (2, 'sent')], default=0),
        ),
    ]
