# Generated by Django 2.2.2 on 2020-04-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_auto_20200410_2254"),
    ]

    operations = [
        migrations.RenameField(model_name="request", old_name="requester", new_name="client",),
    ]
