# Generated by Django 2.2.2 on 2020-04-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.CreateModel(
            name='RequestRole',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True)),
                ('party', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Party'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyRole',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True)),
                ('party', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Party'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='party_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='users.Party',
            ),
            preserve_default=False,
        ),
    ]
