# Generated by Django 2.2.2 on 2020-04-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200410_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrole',
            name='party',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='request_role',
                serialize=False,
                to='users.Party',
            ),
        ),
        migrations.AlterField(
            model_name='supplyrole',
            name='party',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='supply_role',
                serialize=False,
                to='users.Party',
            ),
        ),
    ]
