# Generated by Django 2.2.2 on 2019-12-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=512, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modification_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bar',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='longitude',
        ),
        migrations.AddField(
            model_name='bar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='map_url',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11927.61444143628!2d-4.7640099670346325!3d41.636214867871715!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd476d116ecdca61%3A0x11e92d58476c740a!2sEl%20Rincon%20del%20Erizo!5e0!3m2!1ses!2ses!4v1577201234588!5m2!1ses!2ses', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerts', to='core.Bar'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerts', to='core.Band'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='bar',
            name='bands',
            field=models.ManyToManyField(related_name='bars', through='core.Concert', to='core.Band'),
        ),
    ]
