# Generated by Django 2.2.2 on 2019-12-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191225_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='description',
        ),
        migrations.AddField(
            model_name='concert',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
