# Generated by Django 2.2.2 on 2020-04-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20191225_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
