# Generated by Django 2.2.2 on 2020-04-09 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_concert_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bands', to=settings.AUTH_USER_MODEL),
        ),
    ]
