name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: |
        make up
    - name: Run Tests
      run: |
        make test
    - name: Stop containers
      run: |
        make down
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: src/.coverage
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: .
