name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: |
        make up
    - name: Run Tests
      run: |
        make test
    - name: Stop containers
      run: |
        make down
    - name: Publish coverage
      run: |
        cd src
        python3 -m pip install -U pip setuptools
        python3 -m pip install -U coveralls
        python3 -m coveralls
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: .
